In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, 6, 3],
    [7, 8, 3],
    [1, 6, 6]
])

A

array([[1, 6, 3],
       [7, 8, 3],
       [1, 6, 6]])

In [4]:
B = np.array([2, 3, 6])
B = B.T

B

array([2, 3, 6])

In [5]:
C = A.dot(B)
C

array([38, 56, 56])